version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: iot_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: